services:
  runner:
    image: github-runner
    env_file: ".env"
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M
    restart: no

