name: 2.Build .NET Core

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      project-path:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: release
      artifact-path:
        required: true
        type: string


jobs:
  project:
    runs-on: [self-hosted, Linux, X64, self-hosted-ubuntu-2204]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Install dependencies
        working-directory: ${{ inputs.project-path }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ inputs.project-path }}
        run: dotnet build --configuration Release --no-restore

      - run: ls -lah ${{ inputs.artifact-path }}

      - name: Armazenando Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}