name: 2.Build .NET Core

# on:
#   workflow_run:
#     workflows: ["1.Test .NET Core"]
#     types:
#       - completed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, self-hosted-ubuntu-2204]

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.nuget/packages
      #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nuget-
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
