name: 3.Deploy .NET Core

# on:
#   workflow_run:
#     workflows: ["2.Build .NET Core"]
#     types:
#       - completed
on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, self-hosted-ubuntu-2204]

    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -lah
