name: Test, Build, Deploy

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    testes:
        uses: salgueiroso/actions/.github/workflows/test.yaml@master
        with:
            dotnet-version: 6.0.x
            project-path: ${{ github.workspace }}

    compilacao:
        uses: salgueiroso/actions/.github/workflows/build.yaml@master
        with:
            dotnet-version: 6.0.x
            project-path: ${{ github.workspace }}
            artifact-name: "artefatos-${{ github.ref_name }}"
            artifact-path: ${{ github.workspace }}/src/app/bin/Release/net6.0/*

