name: Test, Build, Deploy

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    testes:
        runs-on: [self-hosted, Linux, X64, self-hosted-ubuntu-2204]
        steps:
            - uses: actions/checkout@v4
            - uses: salgueiroso/actions/acts/test-tdd-dotnetcore@master
              with:
                dotnet-version: 6.0.x
                project-path: ${{ github.workspace }}

    compilacao:
        runs-on: [self-hosted, Linux, X64, self-hosted-ubuntu-2204]
        needs: testes
        steps:
            - uses: actions/checkout@v4
            - uses: salgueiroso/actions/acts/build@master
              with:
                dotnet-version: 6.0.x
                project-path: ${{ github.workspace }}
                artifact-name: "artefatos-${{ github.ref_name }}"
                artifact-path: ${{ github.workspace }}/src/app/bin/Release/net6.0/win-x64/publish/*


    # deploy:
    #     needs: compilacao
    #     uses: salgueiroso/actions/.github/workflows/deploy.yaml@master



