name: Test, Build, Deploy

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    test:
        uses: salgueiroso/actions/.github/workflows/test.yaml@master
        with:
            dotnet-version: 6.0.x
