name: 1.Test .NET Core

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      project-path:
        required: true
        type: string


jobs:
  unitarios:
    runs-on: [self-hosted, Linux, X64, self-hosted-ubuntu-2204]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          cache: true

      - name: Install dependencies
        working-directory: ${{ inputs.project-path }}
        run: dotnet restore
        
      - name: Test
        working-directory: ${{ inputs.project-path }}
        run: dotnet test
